apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: arduino-currents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
          resources:
           requests:
            cpu: "0.5"
            memory: 0.5Gi
           limits:
            cpu: "1"
            memory: 1Gi
