apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: arduino-currents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          resources:
           limits:
             memory: 800Mi
             cpu: "0.2"
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf
              readOnly: true  # Make the volume read-only
          env:
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: password
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
            
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: arduino-currents
data:
  telegraf.conf: |
    [[inputs.mqtt_consumer]]
      ## Broker URLs for the MQTT server or cluster.
      servers = ["tcp:mqtt-broker-service:1883"]  # Update with the service name of your MQTT broker

      ## Topics that will be subscribed to.
      topics = [
        "arduino_currents",
      ]

      ## Data format to consume.
      data_format = "influx"

    [[outputs.influxdb]]
      urls = ["http://influxdb-service:8086"]  # update with your InfluxDB server URL
      database = "currents"
      username = "${INFLUXDB_USERNAME}"
      password = "${INFLUXDB_PASSWORD}"
      precision = "s"
      timeout = "5s"

